// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::http::ReqwestClient;
use crate::options::InstrumentationClientInfo;
use gax::options::RequestOptions;
use tracing::Span;
use tracing::span::Record;

// #[derive(OtelAttributes)]
#[derive(Debug, Clone)]
// TODO(#3239): Potentially replace with a derive macro
#[allow(dead_code)]
pub(crate) struct HttpSpanInfo {
    // Attributes for OpenTelemetry SDK interop
    // #[otel(key = "otel.kind")]
    otel_kind: &'static str,  // "Client"
    // #[otel(key = "otel.name")]
    otel_name: String,        // "{METHOD} {url.template}" or "{METHOD}"
    // #[otel(key = "otel.status", phase = "response")]
    otel_status: &'static str, // "Unset", "Ok", "Error"

    // OpenTelemetry Semantic Conventions
    // #[otel(key = "rpc.system")]
    rpc_system: &'static str, // "http"
    // #[otel(key = "http.request.method")]
    http_request_method: String,
    // #[otel(key = "server.address")]
    server_address: Option<String>, // Host from URL
    // #[otel(key = "server.port")]
    server_port: Option<u16>,      // Port from URL
    // #[otel(key = "url.full")]
    url_full: String,
    // #[otel(key = "url.scheme")]
    url_scheme: Option<String>,
    // #[otel(key = "url.template")]
    url_template: Option<String>, // From RequestOptions.path_template
    // #[otel(key = "url.domain")]
    url_domain: Option<&'static str>,

    // #[otel(key = "http.response.status_code", phase = "response")]
    http_response_status_code: Option<u16>,
    // #[otel(key = "error.type", phase = "response")]
    error_type: Option<&'static str>,
    // #[otel(key = "http.request.resend_count")]
    http_request_resend_count: Option<u32>,

    // Custom GCP Attributes
    // #[otel(key = "gcp.client.service")]
    gcp_client_service: Option<&'static str>,
    // #[otel(key = "gcp.client.version")]
    gcp_client_version: Option<&'static str>,
    // #[otel(key = "gcp.client.repo")]
    gcp_client_repo: &'static str, // "googleapis/google-cloud-rust"
    // #[otel(key = "gcp.client.artifact")]
    gcp_client_artifact: Option<&'static str>,
}

// TODO(#3239): These consts would be generated by a proc macro
impl HttpSpanInfo {
    const KEY_OTEL_KIND: &'static str = "otel.kind";
    const KEY_OTEL_NAME: &'static str = "otel.name";
    const KEY_OTEL_STATUS: &'static str = "otel.status";
    const KEY_RPC_SYSTEM: &'static str = "rpc.system";
    const KEY_HTTP_REQUEST_METHOD: &'static str = "http.request.method";
    const KEY_SERVER_ADDRESS: &'static str = "server.address";
    const KEY_SERVER_PORT: &'static str = "server.port";
    const KEY_URL_FULL: &'static str = "url.full";
    const KEY_URL_SCHEME: &'static str = "url.scheme";
    const KEY_URL_TEMPLATE: &'static str = "url.template";
    const KEY_URL_DOMAIN: &'static str = "url.domain";
    const KEY_HTTP_RESPONSE_STATUS_CODE: &'static str = "http.response.status_code";
    const KEY_ERROR_TYPE: &'static str = "error.type";
    const KEY_HTTP_REQUEST_RESEND_COUNT: &'static str = "http.request.resend_count";
    const KEY_GCP_CLIENT_SERVICE: &'static str = "gcp.client.service";
    const KEY_GCP_CLIENT_VERSION: &'static str = "gcp.client.version";
    const KEY_GCP_CLIENT_REPO: &'static str = "gcp.client.repo";
    const KEY_GCP_CLIENT_ARTIFACT: &'static str = "gcp.client.artifact";

    // TODO(#3239): Remove once used in http.rs
    #[allow(dead_code)]
    pub(crate) fn new(
        _client: &ReqwestClient,
        request: &reqwest::Request,
        options: &RequestOptions,
        instrumentation: Option<&InstrumentationClientInfo>,
        current_attempt: u32,
    ) -> Self {
        let url = request.url();
        let method = request.method();

        let url_template = gax::options::internal::get_path_template(options);
        let otel_name = url_template.map_or_else(
            || method.to_string(),
            |template| format!("{} {}", method, template),
        );

        let http_request_resend_count = if current_attempt > 0 {
            Some(current_attempt)
        } else {
            None
        };

        let (gcp_client_service, gcp_client_version, gcp_client_artifact, url_domain) =
            instrumentation.map_or((None, None, None, None), |info| {
                (
                    Some(info.service_name),
                    Some(info.client_version),
                    Some(info.client_artifact),
                    Some(info.default_host),
                )
            });

        Self {
            rpc_system: "http",
            otel_kind: "Client",
            otel_name,
            otel_status: "Unset",
            http_request_method: method.to_string(),
            server_address: url.host_str().map(String::from),
            server_port: url.port_or_known_default(),
            url_full: url.to_string(),
            url_scheme: Some(url.scheme().to_string()),
            url_template: url_template.map(String::from),
            url_domain,
            http_response_status_code: None,
            error_type: None,
            http_request_resend_count,
            gcp_client_service,
            gcp_client_version,
            gcp_client_repo: "googleapis/google-cloud-rust",
            gcp_client_artifact,
        }
    }

    // TODO(#3239): This method would be generated by a proc macro
    #[allow(dead_code)]
    pub(crate) fn create_span(&self, name: &'static str) -> Span {
        tracing::info_span!(
            name,
            { Self::KEY_OTEL_KIND } = self.otel_kind,
            { Self::KEY_OTEL_NAME } = %self.otel_name,
            { Self::KEY_RPC_SYSTEM } = self.rpc_system,
            { Self::KEY_HTTP_REQUEST_METHOD } = %self.http_request_method,
            { Self::KEY_SERVER_ADDRESS } = self.server_address.as_deref(),
            { Self::KEY_SERVER_PORT } = self.server_port,
            { Self::KEY_URL_FULL } = %self.url_full,
            { Self::KEY_URL_SCHEME } = self.url_scheme.as_deref(),
            { Self::KEY_URL_TEMPLATE } = self.url_template.as_deref(),
            { Self::KEY_URL_DOMAIN } = self.url_domain,
            { Self::KEY_HTTP_REQUEST_RESEND_COUNT } = self.http_request_resend_count,
            { Self::KEY_GCP_CLIENT_SERVICE } = self.gcp_client_service,
            { Self::KEY_GCP_CLIENT_VERSION } = self.gcp_client_version,
            { Self::KEY_GCP_CLIENT_REPO } = self.gcp_client_repo,
            { Self::KEY_GCP_CLIENT_ARTIFACT } = self.gcp_client_artifact,

            // Response phase attributes are initialized with their current values
            { Self::KEY_OTEL_STATUS } = self.otel_status,
            { Self::KEY_HTTP_RESPONSE_STATUS_CODE } = self.http_response_status_code,
            { Self::KEY_ERROR_TYPE } = self.error_type,
        )
    }

    // TODO(#3239): This method would be generated by a proc macro
    #[allow(dead_code)]
    pub(crate) fn record_response_attributes(&self, recorder: &mut Record<'_>) {
        recorder.record(Self::KEY_OTEL_STATUS, &self.otel_status);
        if let Some(val) = self.http_response_status_code {
            recorder.record(Self::KEY_HTTP_RESPONSE_STATUS_CODE, val);
        }
        if let Some(val) = self.error_type {
            recorder.record(Self::KEY_ERROR_TYPE, val);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gax::options::RequestOptions;
    use crate::http::ReqwestClient;
    use crate::options::{ClientConfig, InstrumentationClientInfo};
    use http::Method;
    use reqwest;
    use tracing_subscriber::{fmt, layer::SubscriberExt, util::SubscriberInitExt, Layer};
    use tracing::Level;

    // Helper to create a dummy ReqwestClient
    async fn dummy_client() -> ReqwestClient {
        let config = ClientConfig::default();
        ReqwestClient::new(config, "https://example.com").await.unwrap()
    }

    #[tokio::test]
    async fn test_http_span_info_new_basic() {
        let client = dummy_client().await;
        let request = reqwest::Request::new(Method::GET, "https://example.com/test".parse().unwrap());
        let options = RequestOptions::default();

        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 0);

        assert_eq!(span_info.rpc_system, "http");
        assert_eq!(span_info.otel_kind, "Client");
        assert_eq!(span_info.otel_name, "GET");
        assert_eq!(span_info.otel_status, "Unset");
        assert_eq!(span_info.http_request_method, "GET");
        assert_eq!(span_info.server_address, Some("example.com".to_string()));
        assert_eq!(span_info.server_port, Some(443));
        assert_eq!(span_info.url_full, "https://example.com/test");
        assert_eq!(span_info.url_scheme, Some("https".to_string()));
        assert_eq!(span_info.url_template, None);
        assert_eq!(span_info.url_domain, None);
        assert_eq!(span_info.http_response_status_code, None);
        assert_eq!(span_info.error_type, None);
        assert_eq!(span_info.http_request_resend_count, None);
        assert_eq!(span_info.gcp_client_service, None);
        assert_eq!(span_info.gcp_client_version, None);
        assert_eq!(span_info.gcp_client_repo, "googleapis/google-cloud-rust");
        assert_eq!(span_info.gcp_client_artifact, None);
    }

    #[tokio::test]
    async fn test_http_span_info_new_with_instrumentation() {
        let client = dummy_client().await;
        let request = reqwest::Request::new(Method::POST, "https://test.service.dev:443/v1/items".parse().unwrap());
        let options = RequestOptions::default();
        const INFO: InstrumentationClientInfo = InstrumentationClientInfo {
            service_name: "test.service",
            client_version: "1.2.3",
            client_artifact: "google-cloud-test",
            default_host: "test.service.dev",
        };

        let span_info = HttpSpanInfo::new(&client, &request, &options, Some(&INFO), 0);

        assert_eq!(span_info.gcp_client_service, Some("test.service"));
        assert_eq!(span_info.gcp_client_version, Some("1.2.3"));
        assert_eq!(span_info.gcp_client_artifact, Some("google-cloud-test"));
        assert_eq!(span_info.url_domain, Some("test.service.dev"));
        assert_eq!(span_info.server_address, Some("test.service.dev".to_string()));
        assert_eq!(span_info.server_port, Some(443));
    }

    #[tokio::test]
    async fn test_http_span_info_new_with_path_template() {
        let client = dummy_client().await;
        let request = reqwest::Request::new(Method::GET, "https://example.com/items/123".parse().unwrap());
        let options = gax::options::internal::set_path_template(
            RequestOptions::default(),
            Some("/items/{item_id}".to_string()),
        );

        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 0);

        assert_eq!(span_info.url_template, Some("/items/{item_id}".to_string()));
        assert_eq!(span_info.otel_name, "GET /items/{item_id}");
    }

    #[tokio::test]
    async fn test_http_span_info_new_with_attempt_count() {
        let client = dummy_client().await;
        let request = reqwest::Request::new(Method::GET, "https://example.com/test".parse().unwrap());
        let options = RequestOptions::default();

        // current_attempt is 0 for the first try
        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 0);
        assert_eq!(span_info.http_request_resend_count, None);

        // current_attempt is 1 for the second try (first retry)
        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 1);
        assert_eq!(span_info.http_request_resend_count, Some(1));

        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 5);
        assert_eq!(span_info.http_request_resend_count, Some(5));
    }

    #[tokio::test]
    async fn test_create_span() {
        let client = dummy_client().await;
        let request = reqwest::Request::new(Method::GET, "https://example.com/test".parse().unwrap());
        let options = RequestOptions::default();
        let span_info = HttpSpanInfo::new(&client, &request, &options, None, 0);

        let (subscriber, layer) = tracing_subscriber::test::MockSubscriber::new();
        tracing_subscriber::registry().with(layer).init();

        let span = span_info.create_span("test_span");
        let _enter = span.enter();

        // TODO(#3239): Add assertions on captured span attributes
    }
}
