[package]
name                   = "auth-uniffi"
version                = "0.1.0"
authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]
name       = "auth_uniffi"

[dependencies]
uniffi            = { workspace = true, features = ["cli", "tokio"] }
thiserror         = { workspace = true }
google-cloud-auth = { workspace = true, features = ["default-rustls-provider"] }
http              = { workspace = true }
tokio             = { workspace = true, features = ["rt-multi-thread"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
