[package]
name                   = "swift-packager"
version                = "0.1.0"
authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
zip = { workspace = true }
clap = { workspace = true, features = ["derive", "std"] }
cargo_metadata = { workspace = true }
rust_auth_core_builder = { path = "../../src/rust_auth_core_builder" }
