[package]
name = "rust_auth_core_builder"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
